### ISSUE TITLE
哥们，都是mum的题么

### ISSUE THREAD

**Issue by njzhenghao** [sachinkeshav/JavaExam#1]
这学校如何啊

**Comment by sachinkeshav** [comment]
English please!

**Comment by njzhenghao** [comment]
sorry about that.
These are the questions of mum and did you graduate from mum?

**Comment by sachinkeshav** [comment]
Yes, these are MUM questions. And yes, I graduated from MUM.

**Comment by njzhenghao** [comment]
- Sorry, I haven’t replied to you for so long.
- I'm applying for this school now.and i want know something from you ,thanks.
- Can the school really provide us with internships or employment opportunities?
- In addition to the tuition fee of about $40,000, are there other invisible charges?
- How is the school's diploma social recognition?
- I am a Java developer, what is the employment situation, salary status?

**Comment by sachinkeshav** [comment]
Send me an email, I will be happy to assist you. My email is sachinkeshav at gmail dot com!
